### ISSUE TITLE
router problem /posts/:postId

### ISSUE THREAD

**Issue by klebershimabuku** [klebershimabuku/learning-react#1]
When this route is rendered the `PostsPage` component is being rendered instead of just render the `PostPage` component.

/cc @ryanflorence, could you please give me some help to fix this?

**Comment by klebershimabuku** [comment]
Just fixed. Sorry! :)

**Comment by ryanflorence** [comment]
![](https://38.media.tumblr.com/tumblr_lzs8xyhY3H1rnxfsso1_500.gif)
